import type { AdminOverviewResponse } from "@/lib/api/types";

export const ADMIN_TELEMETRY_FIXTURE: AdminOverviewResponse = {
  stats: {
    userCount: 24,
    adminCount: 3,
    documentCount: 186,
    processingCount: 7,
    jobCount: 241,
    failedJobCount: 9,
    conversationCount: 68,
    recentMessageCount: 312,
    chunkCount: 48216,
    sampledChunkCount: 120,
    sourceCitationCount: 896,
    messagesLast24h: 74,
    documentsLast7d: 18,
  },
  breakdowns: {
    documentsByStatus: { ready: 161, processing: 7, failed: 18 },
    documentsBySourceType: { pdf: 118, website: 51, database: 17 },
    jobsByStatus: { succeeded: 204, running: 12, queued: 16, failed: 9 },
    messagesByRole: { user: 164, assistant: 148 },
    chunksBySourceType: { pdf: 32840, website: 11920, database: 3456 },
  },
  users: [
    {
      id: "fixture-user-admin",
      email: "admin@iota.local",
      name: "Iota Admin",
      role: "admin",
      createdAt: "2026-05-01T04:00:00.000Z",
      documentCount: 42,
      processingCount: 2,
      failedJobCount: 1,
      conversationCount: 18,
      recentMessageCount: 74,
      chunkCount: 12684,
      sampledChunkCount: 38,
      sourceCitationCount: 212,
      lastActivityAt: "2026-05-11T09:15:00.000Z",
    },
    {
      id: "fixture-user-member",
      email: "member@iota.local",
      name: "Research Member",
      role: "user",
      createdAt: "2026-05-03T02:30:00.000Z",
      documentCount: 31,
      processingCount: 1,
      failedJobCount: 2,
      conversationCount: 12,
      recentMessageCount: 48,
      chunkCount: 8421,
      sampledChunkCount: 24,
      sourceCitationCount: 144,
      lastActivityAt: "2026-05-11T08:30:00.000Z",
    },
  ],
  recentDocuments: [
    {
      id: "fixture-admin-doc-1",
      userId: "fixture-user-admin",
      sourceType: "pdf",
      title: "Machine Learning Systems Handbook.pdf",
      status: "ready",
      chunkCount: 1420,
      createdAt: "2026-05-09T08:20:00.000Z",
      updatedAt: "2026-05-10T08:20:00.000Z",
      originalFilename: "machine-learning-systems-handbook.pdf",
      storageBucket: "documents",
      storagePath: "fixture-user-admin/ml-systems.pdf",
      contentHash: "8fd31b7c98f14d9e9f3d0ca713d6",
      metadata: { pages: 184, language: "en" },
    },
    {
      id: "fixture-admin-doc-2",
      userId: "fixture-user-member",
      sourceType: "website",
      title: "Internal onboarding knowledge base",
      status: "processing",
      chunkCount: 386,
      createdAt: "2026-05-10T06:45:00.000Z",
      updatedAt: "2026-05-10T07:05:00.000Z",
      url: "https://docs.example.com/onboarding",
      metadata: { depth: 2, pagesVisited: 17 },
    },
  ],
  recentJobs: [
    {
      id: "fixture-job-1",
      userId: "fixture-user-admin",
      documentId: "fixture-admin-doc-1",
      jobType: "pdf",
      status: "succeeded",
      stage: "storing",
      createdAt: "2026-05-10T08:00:00.000Z",
      startedAt: "2026-05-10T08:01:00.000Z",
      completedAt: "2026-05-10T08:05:00.000Z",
      metadata: { chunks: 1420 },
    },
    {
      id: "fixture-job-2",
      userId: "fixture-user-member",
      documentId: "fixture-admin-doc-2",
      jobType: "website",
      status: "running",
      stage: "embedding",
      createdAt: "2026-05-10T07:00:00.000Z",
      startedAt: "2026-05-10T07:01:00.000Z",
      metadata: { currentPage: "overview" },
    },
  ],
  recentMessages: [
    {
      id: "fixture-message-1",
      userId: "fixture-user-admin",
      conversationId: "fixture-thread-1",
      role: "user",
      content: "Summarize the ingestion pipeline and identify failed sources.",
      model: "routing",
      metadata: { mode: "auto" },
      createdAt: "2026-05-11T09:05:00.000Z",
    },
    {
      id: "fixture-message-2",
      userId: "fixture-user-admin",
      conversationId: "fixture-thread-1",
      role: "assistant",
      content: "The pipeline extracts, chunks, embeds, and stores source content while preserving citations.",
      model: "answer-model",
      metadata: { citations: 2 },
      createdAt: "2026-05-11T09:06:00.000Z",
    },
  ],
  sampledChunks: [
    {
      id: "fixture-chunk-1",
      userId: "fixture-user-admin",
      documentId: "fixture-admin-doc-1",
      chunkIndex: 42,
      tokenCount: 318,
      sourceType: "pdf",
      pageNumber: 42,
      metadata: { heading: "Retrieval architecture" },
      createdAt: "2026-05-10T08:04:00.000Z",
    },
    {
      id: "fixture-chunk-2",
      userId: "fixture-user-member",
      documentId: "fixture-admin-doc-2",
      chunkIndex: 12,
      tokenCount: 224,
      sourceType: "website",
      url: "https://docs.example.com/onboarding",
      metadata: { heading: "Workspace defaults" },
      createdAt: "2026-05-10T07:08:00.000Z",
    },
  ],
  recentSources: [
    {
      id: "fixture-source-1",
      userId: "fixture-user-admin",
      messageId: "fixture-message-2",
      documentId: "fixture-admin-doc-1",
      chunkId: "fixture-chunk-1",
      score: 0.91,
      snippet: "The retrieval stage constrains context before generation and attaches citations.",
      metadata: { rank: 1 },
      createdAt: "2026-05-11T09:06:00.000Z",
    },
  ],
  timeline: [
    {
      type: "document",
      userId: "fixture-user-admin",
      title: "Machine Learning Systems Handbook.pdf",
      status: "ready",
      createdAt: "2026-05-10T08:20:00.000Z",
    },
    {
      type: "job",
      userId: "fixture-user-member",
      title: "Internal onboarding knowledge base",
      status: "running",
      createdAt: "2026-05-10T07:05:00.000Z",
    },
  ],
};
