"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_workspace_badge from './dashboard-workspace-badge.bones.json'
import _dashboard_user_card from './dashboard-user-card.bones.json'
import _dashboard_overview from './dashboard-overview.bones.json'
import _documents_registry from './documents-registry.bones.json'
import _chat_workspace from './chat-workspace.bones.json'
import _settings_page from './settings-page.bones.json'
import _admin_telemetry from './admin-telemetry.bones.json'

configureBoneyard({"color":"rgba(26, 26, 26, 0.075)","darkColor":"rgba(255, 255, 255, 0.08)","animate":"shimmer","shimmerColor":"rgba(255, 255, 255, 0.42)","darkShimmerColor":"rgba(255, 255, 255, 0.14)","speed":"1.9s","shimmerAngle":112,"stagger":12,"transition":240})

registerBones({
  "dashboard-workspace-badge": _dashboard_workspace_badge,
  "dashboard-user-card": _dashboard_user_card,
  "dashboard-overview": _dashboard_overview,
  "documents-registry": _documents_registry,
  "chat-workspace": _chat_workspace,
  "settings-page": _settings_page,
  "admin-telemetry": _admin_telemetry,
})
